### ISSUE TITLE
更新马娘和卡池数据失败

### ISSUE THREAD

**Issue by GudaTom** [assassingyk/umagacha#1]
更新失败……HTTPSConnectionPool(host='wiki.biligame.com', port=443): Max retries exceeded with url: /umamusume/%E5%8D%A1%E6%B1%A0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D371F4A7F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

请问大佬这应该怎么解决

**Comment by assassingyk** [comment]
你这是没用梯子但是还留着proxies的配置吧……直连就把proxies的内容改成空的就行了
